lista = []
print(lista)
print(len(lista))
lista.append(1)
lista.append(5)
lista.append('Ana')
lista.append('Pedro')
print(lista)
print(len(lista))
lista.remove(5)
print(lista)
print(len(lista))
lista.reverse()
print(lista)